### ISSUE TITLE
search class looks strange with extra inline function

### ISSUE THREAD

**Issue by danmarsden** [PukunuiMalaysia/moodle-mod_scratchpad#11]
this function looks weird to me - Moodle has used core_search\base_activity since Moodle 3.2 - and I assume you don't need to support older versions so you should be able to remove that handling and just extend core_search\base_activity in your search class.

https://github.com/PukunuiMalaysia/scratchpad/blob/MOODLE_310_STABLE/classes/search/activity.php#L30-L38

**Comment by danmarsden** [comment]
probably the same for your search/entry class too.

**Comment by tengkualauddin** [comment]
Removed search classes folder
