### ISSUE TITLE
adding a new scratchpad activity to a course triggers a db error

### ISSUE THREAD

**Issue by danmarsden** [PukunuiMalaysia/moodle-mod_scratchpad#16]
Debug info: ERROR: invalid input syntax for type bigint: ""
SELECT cm.*, m.name, md.name AS modname
FROM mdl_course_modules cm
JOIN mdl_modules md ON md.id = cm.module
JOIN mdl_scratchpad m ON m.id = cm.instance

WHERE cm.id = $1 AND md.name = $2

[array (
0 => '',
1 => 'scratchpad',
)]
Error code: dmlreadexception×Dismiss this notification
Stack trace:
line 494 of /lib/dml/moodle_database.php: dml_read_exception thrown
line 293 of /lib/dml/moodle_read_slave_trait.php: call to moodle_database->query_end()
line 341 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->read_slave_query_end()
line 1027 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
line 1679 of /lib/dml/moodle_database.php: call to pgsql_native_moodle_database->get_records_sql()
line 1266 of /lib/datalib.php: call to moodle_database->get_record_sql()
line 70 of /mod/scratchpad/mod_form.php: call to get_coursemodule_from_id()
line 214 of /lib/formslib.php: call to mod_scratchpad_mod_form->definition()
line 131 of /course/moodleform_mod.php: call to moodleform->__construct()
line 152 of /course/modedit.php: call to moodleform_mod->__construct()

**Comment by danmarsden** [comment]
looks like a check to see if $current_id is empty should be added before trying to use it.

**Comment by tengkualauddin** [comment]
Since get_coursemodule_from_id passing empty cmid for newly created course module,this triggered error for Postgre SQL. Added checking to skip if cmid is empty
