### ISSUE TITLE
plugins db entry description needs improvement

### ISSUE THREAD

**Issue by danmarsden** [PukunuiMalaysia/moodle-mod_scratchpad#3]
"Scratchpad module, based on Journal module" - not really enough to describe what the plugin does and how it improves on the journal module - can you add some more detail to the plugins db description please? :-)

**Comment by tengkualauddin** [comment]
Updated README.md

**Comment by danmarsden** [comment]
Thansk @tengkualauddin - I see it's improved a little, but now you've removed the reference to journal completely? - I'd expect to see something along the lines of:

This plugin is based on the Journal activity in Moodle, but adds the following "cool things"
1) it does this by X

2) It also does this other thing better

3) and more!! 

I see Vinny has access to edit the plugin too - I'd suggest you ask him to tidy that up a bit more for you! :-)
