### ISSUE TITLE
coursename/category names should be passed through format_string or format_text

### ISSUE THREAD

**Issue by danmarsden** [PukunuiMalaysia/moodle-mod_scratchpad#8]
eg: 
https://github.com/PukunuiMalaysia/scratchpad/blob/MOODLE_310_STABLE/download.php#L144

when displaying content like the course name, category name, activity names etc, - you need to pass these variables through moodle's output functions - more info here:
https://docs.moodle.org/dev/Output_functions

**Comment by tengkualauddin** [comment]
Added format_text for cleanup string
